POST http://localhost:8000/api/customers
Content-Type: application/json

{
    "title": "",
    "first_name": "Peter",
    "surname": "Smith",
    "mobile": 57578780987,
    "email": "peteetr0rr.smith@gmail.com",
    "home_address": {
        "home_address_line_1": "Castle Dawson 15",
        "home_address_line_2": "",
        "home_town": "Maynooth",
        "home_city": "Maynooth",
        "home_eircode": "WS43YZ"
    },
    "shipping_address": {
        "shipping_address_line_1": "Castle Dawson 15",
        "shipping_address_line_2": "",
        "shipping_town": "Maynooth",
        "shipping_city": "Maynooth",
        "shipping_eircode": "WS43YZ"
    }
}